# Generated by Django 5.2.4 on 2025-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='generated_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
